// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_VERSION_BLD 16359173
#define UNITY_VERSION_UNDER_HASH "6000.0.62f1_f99f05b3e950"
#define UNITY_VERSION_PARENS_HASH "6000.0.62f1 (f99f05b3e950)"
#define UNITY_VERSION_WIN "6000.0.62.16359173"
