// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_COMPANY "Unity Technologies"
#define UNITY_COPYRIGHT "(c) 2005-2025 Unity Technologies. All rights reserved."
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 6000
#define UNITY_VERSION_MAJ 0
#define UNITY_VERSION_MIN 62
#define UNITY_IS_BETA 0
