// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_VERSION_BLD 8014874
#define UNITY_VERSION_UNDER_HASH "6000.4.2f1_7a4c1aeef971"
#define UNITY_VERSION_PARENS_HASH "6000.4.2f1 (7a4c1aeef971)"
#define UNITY_VERSION_WIN "6000.4.2.8014874"
