// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由文件枚举生成器自动生成
//     生成时间: 2026-02-28 14:53:42
//     源目录: E:/unity/xiangmu/Slay the Spire/Assets/Art/Image/ui/powers/128
//     文件过滤: *.png
// </auto-generated>
// ------------------------------------------------------------------------------

using System;


    /// <summary>
    /// 文件名称枚举
    /// 自动从目录文件生成
    /// </summary>
    public enum BuffName_E
    {
        /// <summary>
        /// 文件: accuracy
        /// 路径: 128\accuracy.png
        /// </summary>
        accuracy = 0,

        /// <summary>
        /// 文件: afterImage
        /// 路径: 128\afterImage.png
        /// </summary>
        afterImage = 1,

        /// <summary>
        /// 文件: ai
        /// 路径: 128\ai.png
        /// </summary>
        ai = 2,

        /// <summary>
        /// 文件: amplify
        /// 路径: 128\amplify.png
        /// </summary>
        amplify = 3,

        /// <summary>
        /// 文件: anger
        /// 路径: 128\anger.png
        /// </summary>
        anger = 4,

        /// <summary>
        /// 文件: armor
        /// 路径: 128\armor.png
        /// </summary>
        armor = 5,

        /// <summary>
        /// 文件: artifact
        /// 路径: 128\artifact.png
        /// </summary>
        artifact = 6,

        /// <summary>
        /// 文件: attackBurn
        /// 路径: 128\attackBurn.png
        /// </summary>
        attackBurn = 7,

        /// <summary>
        /// 文件: backAttack
        /// 路径: 128\backAttack.png
        /// </summary>
        backAttack = 8,

        /// <summary>
        /// 文件: backAttack2
        /// 路径: 128\backAttack2.png
        /// </summary>
        backAttack2 = 9,

        /// <summary>
        /// 文件: barricade
        /// 路径: 128\barricade.png
        /// </summary>
        barricade = 10,

        /// <summary>
        /// 文件: beat
        /// 路径: 128\beat.png
        /// </summary>
        beat = 11,

        /// <summary>
        /// 文件: berserk
        /// 路径: 128\berserk.png
        /// </summary>
        berserk = 12,

        /// <summary>
        /// 文件: bias
        /// 路径: 128\bias.png
        /// </summary>
        bias = 13,

        /// <summary>
        /// 文件: blur
        /// 路径: 128\blur.png
        /// </summary>
        blur = 14,

        /// <summary>
        /// 文件: book
        /// 路径: 128\book.png
        /// </summary>
        book = 15,

        /// <summary>
        /// 文件: brutality
        /// 路径: 128\brutality.png
        /// </summary>
        brutality = 16,

        /// <summary>
        /// 文件: buffer
        /// 路径: 128\buffer.png
        /// </summary>
        buffer = 17,

        /// <summary>
        /// 文件: burst
        /// 路径: 128\burst.png
        /// </summary>
        burst = 18,

        /// <summary>
        /// 文件: carddraw
        /// 路径: 128\carddraw.png
        /// </summary>
        carddraw = 19,

        /// <summary>
        /// 文件: cExplosion
        /// 路径: 128\cExplosion.png
        /// </summary>
        cExplosion = 20,

        /// <summary>
        /// 文件: channel
        /// 路径: 128\channel.png
        /// </summary>
        channel = 21,

        /// <summary>
        /// 文件: choke
        /// 路径: 128\choke.png
        /// </summary>
        choke = 22,

        /// <summary>
        /// 文件: closeUp
        /// 路径: 128\closeUp.png
        /// </summary>
        closeUp = 23,

        /// <summary>
        /// 文件: combust
        /// 路径: 128\combust.png
        /// </summary>
        combust = 24,

        /// <summary>
        /// 文件: confusion
        /// 路径: 128\confusion.png
        /// </summary>
        confusion = 25,

        /// <summary>
        /// 文件: conserve
        /// 路径: 128\conserve.png
        /// </summary>
        conserve = 26,

        /// <summary>
        /// 文件: constricted
        /// 路径: 128\constricted.png
        /// </summary>
        constricted = 27,

        /// <summary>
        /// 文件: controlled_change
        /// 路径: 128\controlled_change.png
        /// </summary>
        controlled_change = 28,

        /// <summary>
        /// 文件: corruption
        /// 路径: 128\corruption.png
        /// </summary>
        corruption = 29,

        /// <summary>
        /// 文件: curiosity
        /// 路径: 128\curiosity.png
        /// </summary>
        curiosity = 30,

        /// <summary>
        /// 文件: darkembrace
        /// 路径: 128\darkembrace.png
        /// </summary>
        darkembrace = 31,

        /// <summary>
        /// 文件: defenseNext
        /// 路径: 128\defenseNext.png
        /// </summary>
        defenseNext = 32,

        /// <summary>
        /// 文件: demonForm
        /// 路径: 128\demonForm.png
        /// </summary>
        demonForm = 33,

        /// <summary>
        /// 文件: deva
        /// 路径: 128\deva.png
        /// </summary>
        deva = 34,

        /// <summary>
        /// 文件: deva2
        /// 路径: 128\deva2.png
        /// </summary>
        deva2 = 35,

        /// <summary>
        /// 文件: devotion
        /// 路径: 128\devotion.png
        /// </summary>
        devotion = 36,

        /// <summary>
        /// 文件: dexterity
        /// 路径: 128\dexterity.png
        /// </summary>
        dexterity = 37,

        /// <summary>
        /// 文件: doubleDamage
        /// 路径: 128\doubleDamage.png
        /// </summary>
        doubleDamage = 38,

        /// <summary>
        /// 文件: doubleTap
        /// 路径: 128\doubleTap.png
        /// </summary>
        doubleTap = 39,

        /// <summary>
        /// 文件: draw
        /// 路径: 128\draw.png
        /// </summary>
        draw = 40,

        /// <summary>
        /// 文件: draw2
        /// 路径: 128\draw2.png
        /// </summary>
        draw2 = 41,

        /// <summary>
        /// 文件: echo
        /// 路径: 128\echo.png
        /// </summary>
        echo = 42,

        /// <summary>
        /// 文件: end_turn_death
        /// 路径: 128\end_turn_death.png
        /// </summary>
        end_turn_death = 43,

        /// <summary>
        /// 文件: energized_blue
        /// 路径: 128\energized_blue.png
        /// </summary>
        energized_blue = 44,

        /// <summary>
        /// 文件: energized_green
        /// 路径: 128\energized_green.png
        /// </summary>
        energized_green = 45,

        /// <summary>
        /// 文件: entangle
        /// 路径: 128\entangle.png
        /// </summary>
        entangle = 46,

        /// <summary>
        /// 文件: envenom
        /// 路径: 128\envenom.png
        /// </summary>
        envenom = 47,

        /// <summary>
        /// 文件: establishment
        /// 路径: 128\establishment.png
        /// </summary>
        establishment = 48,

        /// <summary>
        /// 文件: evolve
        /// 路径: 128\evolve.png
        /// </summary>
        evolve = 49,

        /// <summary>
        /// 文件: explosive
        /// 路径: 128\explosive.png
        /// </summary>
        explosive = 50,

        /// <summary>
        /// 文件: fading
        /// 路径: 128\fading.png
        /// </summary>
        fading = 51,

        /// <summary>
        /// 文件: fasting
        /// 路径: 128\fasting.png
        /// </summary>
        fasting = 52,

        /// <summary>
        /// 文件: firebreathing
        /// 路径: 128\firebreathing.png
        /// </summary>
        firebreathing = 53,

        /// <summary>
        /// 文件: flameBarrier
        /// 路径: 128\flameBarrier.png
        /// </summary>
        flameBarrier = 54,

        /// <summary>
        /// 文件: flex
        /// 路径: 128\flex.png
        /// </summary>
        flex = 55,

        /// <summary>
        /// 文件: flight
        /// 路径: 128\flight.png
        /// </summary>
        flight = 56,

        /// <summary>
        /// 文件: focus
        /// 路径: 128\focus.png
        /// </summary>
        focus = 57,

        /// <summary>
        /// 文件: forcefield
        /// 路径: 128\forcefield.png
        /// </summary>
        forcefield = 58,

        /// <summary>
        /// 文件: frail
        /// 路径: 128\frail.png
        /// </summary>
        frail = 59,

        /// <summary>
        /// 文件: fumes
        /// 路径: 128\fumes.png
        /// </summary>
        fumes = 60,

        /// <summary>
        /// 文件: heartDef
        /// 路径: 128\heartDef.png
        /// </summary>
        heartDef = 61,

        /// <summary>
        /// 文件: heatsink
        /// 路径: 128\heatsink.png
        /// </summary>
        heatsink = 62,

        /// <summary>
        /// 文件: hello
        /// 路径: 128\hello.png
        /// </summary>
        hello = 63,

        /// <summary>
        /// 文件: hex
        /// 路径: 128\hex.png
        /// </summary>
        hex = 64,

        /// <summary>
        /// 文件: hymn
        /// 路径: 128\hymn.png
        /// </summary>
        hymn = 65,

        /// <summary>
        /// 文件: infiniteBlades
        /// 路径: 128\infiniteBlades.png
        /// </summary>
        infiniteBlades = 66,

        /// <summary>
        /// 文件: infinitegreen
        /// 路径: 128\infinitegreen.png
        /// </summary>
        infinitegreen = 67,

        /// <summary>
        /// 文件: intangible
        /// 路径: 128\intangible.png
        /// </summary>
        intangible = 68,

        /// <summary>
        /// 文件: juggernaut
        /// 路径: 128\juggernaut.png
        /// </summary>
        juggernaut = 69,

        /// <summary>
        /// 文件: lessdraw
        /// 路径: 128\lessdraw.png
        /// </summary>
        lessdraw = 70,

        /// <summary>
        /// 文件: like_water
        /// 路径: 128\like_water.png
        /// </summary>
        like_water = 71,

        /// <summary>
        /// 文件: lockon
        /// 路径: 128\lockon.png
        /// </summary>
        lockon = 72,

        /// <summary>
        /// 文件: loop
        /// 路径: 128\loop.png
        /// </summary>
        loop = 73,

        /// <summary>
        /// 文件: magnet
        /// 路径: 128\magnet.png
        /// </summary>
        magnet = 74,

        /// <summary>
        /// 文件: malleable
        /// 路径: 128\malleable.png
        /// </summary>
        malleable = 75,

        /// <summary>
        /// 文件: mantra
        /// 路径: 128\mantra.png
        /// </summary>
        mantra = 76,

        /// <summary>
        /// 文件: mastery
        /// 路径: 128\mastery.png
        /// </summary>
        mastery = 77,

        /// <summary>
        /// 文件: master_protect
        /// 路径: 128\master_protect.png
        /// </summary>
        master_protect = 78,

        /// <summary>
        /// 文件: master_reality
        /// 路径: 128\master_reality.png
        /// </summary>
        master_reality = 79,

        /// <summary>
        /// 文件: master_smite
        /// 路径: 128\master_smite.png
        /// </summary>
        master_smite = 80,

        /// <summary>
        /// 文件: mayhem
        /// 路径: 128\mayhem.png
        /// </summary>
        mayhem = 81,

        /// <summary>
        /// 文件: mental_fortress
        /// 路径: 128\mental_fortress.png
        /// </summary>
        mental_fortress = 82,

        /// <summary>
        /// 文件: minion
        /// 路径: 128\minion.png
        /// </summary>
        minion = 83,

        /// <summary>
        /// 文件: modeShift
        /// 路径: 128\modeShift.png
        /// </summary>
        modeShift = 84,

        /// <summary>
        /// 文件: nightmare
        /// 路径: 128\nightmare.png
        /// </summary>
        nightmare = 85,

        /// <summary>
        /// 文件: nirvana
        /// 路径: 128\nirvana.png
        /// </summary>
        nirvana = 86,

        /// <summary>
        /// 文件: noattack
        /// 路径: 128\noattack.png
        /// </summary>
        noattack = 87,

        /// <summary>
        /// 文件: noBlock
        /// 路径: 128\noBlock.png
        /// </summary>
        noBlock = 88,

        /// <summary>
        /// 文件: noDraw
        /// 路径: 128\noDraw.png
        /// </summary>
        noDraw = 89,

        /// <summary>
        /// 文件: noPain
        /// 路径: 128\noPain.png
        /// </summary>
        noPain = 90,

        /// <summary>
        /// 文件: no_skill
        /// 路径: 128\no_skill.png
        /// </summary>
        no_skill = 91,

        /// <summary>
        /// 文件: no_stance
        /// 路径: 128\no_stance.png
        /// </summary>
        no_stance = 92,

        /// <summary>
        /// 文件: omega
        /// 路径: 128\omega.png
        /// </summary>
        omega = 93,

        /// <summary>
        /// 文件: painfulStabs
        /// 路径: 128\painfulStabs.png
        /// </summary>
        painfulStabs = 94,

        /// <summary>
        /// 文件: panache
        /// 路径: 128\panache.png
        /// </summary>
        panache = 95,

        /// <summary>
        /// 文件: penNib
        /// 路径: 128\penNib.png
        /// </summary>
        penNib = 96,

        /// <summary>
        /// 文件: phantasmal
        /// 路径: 128\phantasmal.png
        /// </summary>
        phantasmal = 97,

        /// <summary>
        /// 文件: platedarmor
        /// 路径: 128\platedarmor.png
        /// </summary>
        platedarmor = 98,

        /// <summary>
        /// 文件: poison
        /// 路径: 128\poison.png
        /// </summary>
        poison = 99,

        /// <summary>
        /// 文件: pressure_points
        /// 路径: 128\pressure_points.png
        /// </summary>
        pressure_points = 100,

        /// <summary>
        /// 文件: reactive
        /// 路径: 128\reactive.png
        /// </summary>
        reactive = 101,

        /// <summary>
        /// 文件: rebound
        /// 路径: 128\rebound.png
        /// </summary>
        rebound = 102,

        /// <summary>
        /// 文件: regen
        /// 路径: 128\regen.png
        /// </summary>
        regen = 103,

        /// <summary>
        /// 文件: regrow
        /// 路径: 128\regrow.png
        /// </summary>
        regrow = 104,

        /// <summary>
        /// 文件: repair
        /// 路径: 128\repair.png
        /// </summary>
        repair = 105,

        /// <summary>
        /// 文件: retain
        /// 路径: 128\retain.png
        /// </summary>
        retain = 106,

        /// <summary>
        /// 文件: ritual
        /// 路径: 128\ritual.png
        /// </summary>
        ritual = 107,

        /// <summary>
        /// 文件: rupture
        /// 路径: 128\rupture.png
        /// </summary>
        rupture = 108,

        /// <summary>
        /// 文件: rushdown
        /// 路径: 128\rushdown.png
        /// </summary>
        rushdown = 109,

        /// <summary>
        /// 文件: sadistic
        /// 路径: 128\sadistic.png
        /// </summary>
        sadistic = 110,

        /// <summary>
        /// 文件: shackle
        /// 路径: 128\shackle.png
        /// </summary>
        shackle = 111,

        /// <summary>
        /// 文件: sharpHide
        /// 路径: 128\sharpHide.png
        /// </summary>
        sharpHide = 112,

        /// <summary>
        /// 文件: shift
        /// 路径: 128\shift.png
        /// </summary>
        shift = 113,

        /// <summary>
        /// 文件: skillBurn
        /// 路径: 128\skillBurn.png
        /// </summary>
        skillBurn = 114,

        /// <summary>
        /// 文件: slow
        /// 路径: 128\slow.png
        /// </summary>
        slow = 115,

        /// <summary>
        /// 文件: split
        /// 路径: 128\split.png
        /// </summary>
        split = 116,

        /// <summary>
        /// 文件: sporeCloud
        /// 路径: 128\sporeCloud.png
        /// </summary>
        sporeCloud = 117,

        /// <summary>
        /// 文件: stasis
        /// 路径: 128\stasis.png
        /// </summary>
        stasis = 118,

        /// <summary>
        /// 文件: static_discharge
        /// 路径: 128\static_discharge.png
        /// </summary>
        static_discharge = 119,

        /// <summary>
        /// 文件: storm
        /// 路径: 128\storm.png
        /// </summary>
        storm = 120,

        /// <summary>
        /// 文件: strength
        /// 路径: 128\strength.png
        /// </summary>
        strength = 121,

        /// <summary>
        /// 文件: surrounded
        /// 路径: 128\surrounded.png
        /// </summary>
        surrounded = 122,

        /// <summary>
        /// 文件: swivel
        /// 路径: 128\swivel.png
        /// </summary>
        swivel = 123,

        /// <summary>
        /// 文件: talk_to_hand
        /// 路径: 128\talk_to_hand.png
        /// </summary>
        talk_to_hand = 124,

        /// <summary>
        /// 文件: the_bomb
        /// 路径: 128\the_bomb.png
        /// </summary>
        the_bomb = 125,

        /// <summary>
        /// 文件: thievery
        /// 路径: 128\thievery.png
        /// </summary>
        thievery = 126,

        /// <summary>
        /// 文件: thorns
        /// 路径: 128\thorns.png
        /// </summary>
        thorns = 127,

        /// <summary>
        /// 文件: thousandCuts
        /// 路径: 128\thousandCuts.png
        /// </summary>
        thousandCuts = 128,

        /// <summary>
        /// 文件: time
        /// 路径: 128\time.png
        /// </summary>
        time = 129,

        /// <summary>
        /// 文件: tools
        /// 路径: 128\tools.png
        /// </summary>
        tools = 130,

        /// <summary>
        /// 文件: unawakened
        /// 路径: 128\unawakened.png
        /// </summary>
        unawakened = 131,

        /// <summary>
        /// 文件: vigor
        /// 路径: 128\vigor.png
        /// </summary>
        vigor = 132,

        /// <summary>
        /// 文件: vulnerable
        /// 路径: 128\vulnerable.png
        /// </summary>
        vulnerable = 133,

        /// <summary>
        /// 文件: wave_of_the_hand
        /// 路径: 128\wave_of_the_hand.png
        /// </summary>
        wave_of_the_hand = 134,

        /// <summary>
        /// 文件: weak
        /// 路径: 128\weak.png
        /// </summary>
        weak = 135,

        /// <summary>
        /// 文件: wireheading
        /// 路径: 128\wireheading.png
        /// </summary>
        wireheading = 136,

        /// <summary>
        /// 文件: wraithForm
        /// 路径: 128\wraithForm.png
        /// </summary>
        wraithForm = 137,
    }

